# PURPOSE: Update EPU index widget when new data is uploaded to GitHub repository
# LAST EDITED: 5/7/2026
# NOTES: This script is derived from and based on Stefan Zweifel's git-auto-commit Action code, which is described
# at https://github.com/stefanzweifel/git-auto-commit-action

name: Update EPU Index Widget on Data Change

on:
  push:
    paths:
      - 'Data/**'  # This is the trigger; only runs when new data is introduced into the repository
  workflow_dispatch:  # Adds a "Run Workflow" button in the UI

permissions:
  contents: write  # This permission is required to allow the computer to make changes
  pages: write # Allow page deployment
  id-token: write # Allow code commits

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check Repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup Pandoc (needed for htmlwidgets)
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install R Packages
        run: |
          install.packages(
            c("htmlwidgets", "stringr", "lubridate", "plotly", "foreign", "haven", "psych", "purrr", "data.table", "tibble", 
              "dplyr", "tidyr", "zoo", "jsonlite", "readr")
              )
        shell: Rscript {0}

      - name: Generate Widget
        run: Rscript R/epuindexbuild.R

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update widget and clean dataset with new data or manual run"
          file_pattern: 'epuindex.html Data/clean/epu_indices.csv'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Uploads entire repository root

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
